JadeIT\CatalogDBundle\Entity\Item:
    type: entity
    table: null
    inheritanceType: JOINED
    discriminatorColumn:
        name: item_type
        type: string
        length: 255
    discriminatorMap:
        item: Item
        category: Category
        tag: Tag
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        active:
            type: boolean
        modified:
            type: datetime
        added:
            type: datetime
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: items
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: items
    lifecycleCallbacks:
        prePersist: [ setAdded, setModified, validate ]
        preUpdate: [ setModified, validate ]
